FROM python:3.11 as django-build

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

RUN python manage.py collectstatic --noinput

FROM nginx:alpine

COPY --from=django-build /app/staticfiles /usr/share/nginx/html/static/

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]