# Generated by Django 3.0 on 2024-06-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20240603_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
