name: test

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.6

    - name: Clone repository
      uses: actions/checkout@v2

    - name: check python and pip version
      run:
      - python --version
      - pip --version

    - name: test
      run: echo "hello world this is TEST pipeline"
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: lint
        run: echo "hello this is LINT pipeline"