name: CI

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.6

    - name: Clone repository
      uses: actions/checkout@v2

    - name: check python and pip version
      run: python --version; pip --version

    - name: install requirements
      run: pip install -r requirements.txt

    - name: check django version
      run: python -m django --version

    - name: test
      run: python manage.py test
      continue-on-error: false

    - name: Check coverage
      id: check_coverage
      run: |
          coverage run --source='.' manage.py test
          coverage report > coverage.txt
          coverage report --fail-under=80

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.6

    - name: Clone repository
      uses: actions/checkout@v2

    - name: check python and pip version
      run: python --version; pip --version

    - name: install requirements
      run: pip install -r requirements.txt

    - name: lint
      run: flake8

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/master'

    steps:
      - name: test check
        run: echo "hello la on build sur master"
