name: test

on: # precise quand est-ce que le job doit s'executer
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: test
      run: echo "hello world this is TEST pipeline"
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: lint
        run: echo "hello this is LINT pipeline"